<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIvoMXou\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIvoMXou/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIvoMXou.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIvoMXou\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIvoMXou\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IvoMXou',
    'container.build_id' => '180f378e',
    'container.build_time' => 1646759170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIvoMXou');
