<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'backend' => [[], ['_controller' => 'App\\Controller\\BackendController::index'], [], [['text', '/backend']], [], []],
    'hotel' => [[], ['_controller' => 'App\\Controller\\HotelController::index'], [], [['text', '/hotel']], [], []],
    'ajouterhotel' => [[], ['_controller' => 'App\\Controller\\HotelController::ajouter'], [], [['text', '/ajouterhotel']], [], []],
    'afficherhotel' => [[], ['_controller' => 'App\\Controller\\HotelController::afficher'], [], [['text', '/afficherhotel']], [], []],
    'modifierhotel' => [['id'], ['_controller' => 'App\\Controller\\HotelController::modifier'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modifierhotel']], [], []],
    'supprimerhotel' => [['id'], ['_controller' => 'App\\Controller\\HotelController::supprimer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/supprimerhotel']], [], []],
    'testbar' => [[], ['_controller' => 'App\\Controller\\HotelController::testbar'], [], [['text', '/testbar']], [], []],
    'listp' => [[], ['_controller' => 'App\\Controller\\HotelController::listp'], [], [['text', '/listp']], [], []],
    'reservation_hotel' => [[], ['_controller' => 'App\\Controller\\ReservationHotelController::index'], [], [['text', '/reservation/hotel']], [], []],
    'createreservationhotel' => [[], ['_controller' => 'App\\Controller\\ReservationHotelController::create'], [], [['text', '/createreservationhotel']], [], []],
    'frontcreatereservationhotel' => [['id'], ['_controller' => 'App\\Controller\\ReservationHotelController::front_create'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/frontcreatereservationhotel']], [], []],
    'updatereservationhotel' => [['id'], ['_controller' => 'App\\Controller\\ReservationHotelController::update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/updatereservationhotel']], [], []],
    'viewreshotel' => [[], ['_controller' => 'App\\Controller\\ReservationHotelController::view'], [], [['text', '/viewreshotel']], [], []],
    'deletereshotel' => [['id'], ['_controller' => 'App\\Controller\\ReservationHotelController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/deletereshotel']], [], []],
];
